### ISSUE TITLE
"PDFObjRef' object is not iterable"

### ISSUE THREAD

**Issue by Aboosh99** [brainstorm/datasheet2svd#2]
Hello Everyone,

I am facing this error "PDFObjRef' object is not iterable" whenever i try to use the standalone exe file application. But when i run the code inside Pycharm, it works like a charm. Note that, I am using pyinstaller to compile the project into standalone exe file. I know this could be happening due to differences in how Python code behaves inside the environment versus a standalone executable. Below is the code 
i am using.

import sys
import os
import camelot
from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QFileDialog, QLabel, QVBoxLayout, QPushButton, QWidget, QProgressBar
import pandas as pd

class PDFtoExcelApp(QWidget):
    def __init__(self):
        super().__init__()
        self.pdf_file_path = None
        self.output_file_path = None
        self.initUI()

    def initUI(self):
        self.setWindowTitle('PDF to Excel Converter')
        self.setGeometry(100, 100, 400, 300)

        layout = QVBoxLayout()

        # Labels for instructions
        self.label = QLabel('Select a PDF file to extract tables:', self)
        layout.addWidget(self.label)

        # Button to select PDF file
        self.select_pdf_btn = QPushButton('Select PDF File', self)
        self.select_pdf_btn.clicked.connect(self.open_pdf_dialog)
        layout.addWidget(self.select_pdf_btn)

        # Button to select output path
        self.output_btn = QPushButton('Select Output Excel File', self)
        self.output_btn.clicked.connect(self.save_output_dialog)
        layout.addWidget(self.output_btn)

        # Convert Button
        self.convert_btn = QPushButton('Convert to Excel', self)
        self.convert_btn.clicked.connect(self.convert_pdf_to_excel)
        layout.addWidget(self.convert_btn)

        # Progress Bar
        self.progress_bar = QProgressBar(self)
        self.progress_bar.setValue(0)
        layout.addWidget(self.progress_bar)

        # Done Label
        self.done_label = QLabel('', self)
        layout.addWidget(self.done_label)

        self.setLayout(layout)

    def open_pdf_dialog(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getOpenFileName(self, "Select PDF File", "", "PDF Files (*.pdf);;All Files (*)",
                                                   options=options)
        if file_name:
            self.pdf_file_path = file_name
            self.label.setText(f'Selected PDF: {file_name}')

    def save_output_dialog(self):
        options = QFileDialog.Options()
        file_name, _ = QFileDialog.getSaveFileName(self, "Save Excel File As", "",
                                                   "Excel Files (*.xlsx);;All Files (*)", options=options)
        if file_name:
            if not file_name.endswith('.xlsx'):
                file_name += '.xlsx'
            self.output_file_path = file_name

    def convert_pdf_to_excel(self):
        try:
            # Check if PDF file and output path are selected
            if not self.pdf_file_path:
                raise ValueError("Please select a PDF file first.")
            if not self.output_file_path:
                raise ValueError("Please select an output path first.")

            # Check file access permissions
            if not os.access(self.pdf_file_path, os.R_OK):
                raise PermissionError("Cannot read the selected PDF file. Please check permissions.")
            if os.path.exists(self.output_file_path) and not os.access(self.output_file_path, os.W_OK):
                raise PermissionError("Cannot write to the selected output file. Please check permissions.")

            # Disable the convert button and update progress bar
            self.convert_btn.setEnabled(False)
            self.progress_bar.setValue(10)

            # Extract tables from PDF
            self.done_label.setText('Extracting tables...')
            QtWidgets.QApplication.processEvents()
            tables = camelot.read_pdf(self.pdf_file_path, pages='all', flavor='stream')
            self.progress_bar.setValue(50)

            if not tables:
                raise ValueError("No tables were found in the PDF file.")

            valid_tables = [table.df for table in tables if isinstance(table.df, pd.DataFrame) and not table.df.empty]

            if len(valid_tables) > 0:
                # Combine all tables into a single DataFrame and remove duplicate headers
                self.done_label.setText('Combining tables...')
                QtWidgets.QApplication.processEvents()
                combined_df = pd.concat(valid_tables, ignore_index=True).drop_duplicates()
                self.progress_bar.setValue(70)

                # Save to Excel
                self.done_label.setText('Saving to Excel...')
                QtWidgets.QApplication.processEvents()
                combined_df.to_excel(self.output_file_path, index=False)
                self.progress_bar.setValue(100)

                self.done_label.setText(f'Conversion Complete! File saved to: {self.output_file_path}')
            else:
                self.done_label.setText('No valid tables found in the selected PDF.')
        except Exception as e:
            self.done_label.setText(f'Error: {str(e)}')
            print(f"Error details: {str(e)}")
        finally:
            # Re-enable the convert button
            self.convert_btn.setEnabled(True)
            self.progress_bar.setValue(0)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    ex = PDFtoExcelApp()
    ex.show()
    sys.exit(app.exec_())

Need your help guys, i don't have that much of experience in coding and i hope someone will help me to solve this error.

**Comment by Aboosh99** [comment]
![Error](https://github.com/user-attachments/assets/f7a6f48f-57bf-4912-8d83-86f3d74fe0e2)

The error looks like this

**Comment by brainstorm** [comment]
This issue has nothing to do with this repository, I'd suggest to ask your question over StackOverflow instead.
